lesson 1:  create three state button and auto generate form
Mihail-tec/webix-custom pull request #1
Opened 2022-04-13 15:32 UTC by Mihail-tec

2022-04-13 15:39 UTC, AlexeyXB requested changes

2022-04-13 15:39 UTC, AlexeyXB commented on index.js
> +        console.log(config);
`сonsole.log` тут лишний

2022-04-13 15:39 UTC, AlexeyXB commented on index.js
> +        config.value = config.states[state];
Может случиться беда, если по какой-то причине стейтов будет больше или меньше 3. Было бы неплохо добавить проверку на существование стейта, перед тем как его использовать.

2022-04-13 15:39 UTC, AlexeyXB commented on index.js
> +        console.log(config);
`сonsole.log` тут лишний

2022-04-13 15:39 UTC, AlexeyXB commented on index.js
> +        console.log(fields);
`сonsole.log` тут лишний

2022-04-14 09:04 UTC, AlexeyXB requested changes

2022-04-14 09:04 UTC, AlexeyXB commented on index.js
> +    for (key in formValues) {
Лучше не использую for in для итерации по объекту. Если все же используешь, то добавляй проверку на hasOwnProperty.

2022-04-14 11:10 UTC, AlexeyXB approved these changes

2022-04-14 17:30 UTC, HelgaListopad requested changes

2022-04-14 17:30 UTC, HelgaListopad commented on index.js
> +        const fields = config.fields.map((el) => {
Стоит проверить, есть ли fields и массив ли это

2022-04-15 10:55 UTC, HelgaListopad approved these changes

2022-04-15 10:55 UTC, merged